services:
  frontend:
    build:
      context: ./frontend

    env_file:
      - ./frontend/.env

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend


  backend:
    build:
      context: ./backend

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgresql://thought_vault:thought_vault_dev@postgres:5432/thought_vault
      ML_SERVICE_URL: http://ml-service:8000

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      postgres:
        condition: service_healthy
      ml-service:
        condition: service_started


  ml-service:
    build:
      context: ./ml-service

    ports:
      - "8000:8000"

    volumes:
      - ./ml-service:/app


  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: thought_vault
      POSTGRES_USER: thought_vault
      POSTGRES_PASSWORD: thought_vault_dev

    ports:
      - "5433:5432"

    volumes:
      - thought_vault_postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U thought_vault -d thought_vault"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  thought_vault_postgres: